### ISSUE TITLE
Spring MVC with Embedded Tomcat

### ISSUE THREAD

**Issue by TranNgocKhoa** [khanhnguyenj/huongdanjava.com#6]
Xin chào anh,
Em thấy có một bài viết nói về Spring Framework với Reactive ở đây https://spring.io/blog/2016/09/22/new-in-spring-5-functional-web-framework
Trong bài họ dùng Spring Reactive chứ không dùng Spring Boot và sau đó nhúng thêm Tomcat để chạy.
Anh có thể viết một bài về Spring MVC thuần với Tomcat nhúng không ạ?
Em xin cảm ơn.

**Comment by khanhnguyenj** [comment]
Thiết nghĩ bài viết này không cần nữa, mình xin close issue này nhé!
